In [19]:
import pandas as pd
import numpy as np

In [32]:
politician = pd.read_csv('../data/final/politician.csv')
politician = politician.drop(['education_level', 'school', 'academic_title','profession','languages','seniority'], axis=1)
politician.tail()

,mp_id,first_name,last_name,birth_date,birth_place,status,country_id
3596,PA267712,Corinne,Marchal-Tarnus,1962-12-28,Villerupt (Meurthe-et-Moselle - France),ASSEMBLEE,3
3597,PA267615,André,Samitier,1935-11-01,Roubia (Aude - France),ASSEMBLEE,3
3598,PA268034,Pierre-Jean,Samot,1934-08-21,Fort-de-france (Martinique - France),ASSEMBLEE,3
3599,PA19726,Alexandra Martin,Alpes-Maritimes,1968-10-25,Nice (Alpes-Maritimes - France),ASSEMBLEE,3
3600,PA19866,Alexandra Martin,Gironde,1976-07-28,Bordeaux (Gironde - France),ASSEMBLEE,3

In [ ]:
politician

In [20]:
df = pd.read_csv('../data/speech/2011_2026/centralized_speeches.csv')
df.tail()

,source_files,id,date,text_speech_brut,text_speech_clean,topic,subtopic1,subtopic2,speaker,link_speaker,role,gender,speech_interjection,quote
3094346,CRI_20260127_013.xml,w1aab3ab1b1b1i01447-4001145,26-01-2026,Je remercie chacun d’entre vous pour la qualit...,Je remercie chacun d’entre vous pour la qualit...,Protéger les mineurs des risques auxquels les ...,NaN,Vote sur l’ensemble,Anne Le Hénanff,NaN,ministre déléguée,NaN,NaN,NaN
3094347,CRI_20260127_013.xml,w1aab3ab1b1b1i01449-4001145,26-01-2026,Comme l’a annoncé le président de la Républiqu...,Comme l’a annoncé le président de la Républiqu...,Protéger les mineurs des risques auxquels les ...,NaN,Vote sur l’ensemble,NaN,NaN,NaN,NaN,NaN,NaN
3094348,CRI_20260127_013.xml,w1aab3ab1b1b1i01452-4001149,26-01-2026,"Prochaine séance, aujourd’hui, à neuf heures :","Prochaine séance, aujourd’hui, à neuf heures :",Ordre du jour de la prochaine séance,NaN,NaN,la présidente,NaN,NaN,NaN,NaN,NaN
3094349,CRI_20260127_013.xml,w1aab3ab1b1b1i01453-4001149,26-01-2026,Questions orales sans débat.,Questions orales sans débat.,Ordre du jour de la prochaine séance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3094350,CRI_20260127_013.xml,w1aab3ab1b1b1i01454-4001149,26-01-2026,La séance est levée.,La séance est levée.,Ordre du jour de la prochaine séance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

si pas de speaker alors row procedureal

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3094351 entries, 0 to 3094350
Data columns (total 14 columns):
 #   Column               Dtype
---  ------               -----
 0   source_files         object
 1   id                   object
 2   date                 object
 3   text_speech_brut     object
 4   text_speech_clean    object
 5   topic                object
 6   subtopic1            object
 7   subtopic2            object
 8   speaker              object
 9   link_speaker         object
 10  role                 object
 11  gender               float64
 12  speech_interjection  object
 13  quote                object
dtypes: float64(1), object(13)
memory usage: 330.5+ MB

- id speaker bindable? 1) id speaker exist in politicians? 2) bind on similare name 
- get data on bind stat
- check data structure, create table in parisparl 2 and push my tables from csv
- documentation

In [33]:
df_preprocessed

,source_files,id,date,text_speech_brut,text_speech_clean,topic,subtopic1,subtopic2,speaker,link_speaker,role,gender,speech_interjection,quote
0,CRI_20111004_083.xml,ANCR201100000159-00069,03-10-2011,. La séance est ouverte.,La séance est ouverte.,NaN,NaN,NaN,le président,NaN,NaN,NaN,NaN,NaN
1,CRI_20111004_083.xml,ANCR201100000159-00073,03-10-2011,Conformément au premier alinéa de l’article 28...,Conformément au premier alinéa de l’article 28...,Ouverture de la session ordinaire,NaN,NaN,le président,NaN,NaN,NaN,NaN,NaN
2,CRI_20111004_083.xml,ANCR201100000159-00076,03-10-2011,"M. le ministre de l’intérieur, de l’outre-mer,...","M. le ministre de l’intérieur, de l’outre-mer,...",Cessation de mandat de députés,NaN,NaN,le président,NaN,NaN,NaN,NaN,NaN
4,CRI_20111004_083.xml,ANCR201100000159-00080,03-10-2011,"M. le président du groupe socialiste, radical,...","M. le président du groupe socialiste, radical,...",Modification de la composition du bureau de l’...,NaN,NaN,le président,NaN,NaN,NaN,NaN,NaN
5,CRI_20111004_083.xml,ANCR201100000159-00085,03-10-2011,"L’ordre du jour appelle la discussion, selon l...","L’ordre du jour appelle la discussion, selon l...",Approbation d’accords internationaux,(Procédure d’examen simplifiée),NaN,le président,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3094343,CRI_20260127_013.xml,w1aab3ab1b1b1i01437-4001140,26-01-2026,Je mets aux voix l’ensemble de la proposition ...,Je mets aux voix l’ensemble de la proposition ...,Protéger les mineurs des risques auxquels les ...,NaN,Vote sur l’ensemble,la présidente,NaN,NaN,NaN,NaN,NaN
3094344,CRI_20260127_013.xml,w1aab3ab1b1b1i01439-4001142,26-01-2026,Voici le résultat du scrutin :,Voici le résultat du scrutin :,Protéger les mineurs des risques auxquels les ...,NaN,Vote sur l’ensemble,la présidente,NaN,NaN,NaN,NaN,NaN
3094345,CRI_20260127_013.xml,w1aab3ab1b1b1i01446-4001144,26-01-2026,La parole est à Mme la ministre déléguée.,La parole est à Mme la ministre déléguée.,Protéger les mineurs des risques auxquels les ...,NaN,Vote sur l’ensemble,la présidente,NaN,NaN,NaN,NaN,NaN
3094346,CRI_20260127_013.xml,w1aab3ab1b1b1i01447-4001145,26-01-2026,Je remercie chacun d’entre vous pour la qualit...,Je remercie chacun d’entre vous pour la qualit...,Protéger les mineurs des risques auxquels les ...,NaN,Vote sur l’ensemble,Anne Le Hénanff,NaN,ministre déléguée,NaN,NaN,NaN
3094348,CRI_20260127_013.xml,w1aab3ab1b1b1i01452-4001149,26-01-2026,"Prochaine séance, aujourd’hui, à neuf heures :","Prochaine séance, aujourd’hui, à neuf heures :",Ordre du jour de la prochaine séance,NaN,NaN,la présidente,NaN,NaN,NaN,NaN,NaN

In [26]:
# Filtre les lignes où 'speaker' n'est pas null
df_preprocessed = df[df['speaker'].notna()]

# Compte les occurrences de chaque valeur non vide dans 'link_speaker'
value_counts = df_preprocessed['link_speaker'].value_counts()

# Nombre de lignes avec link_speaker non vide
nb_link_speaker_non_vide = df_preprocessed['link_speaker'].notna().sum()

# Ratio par rapport à df_preprocessed
ratio_link_speaker = (nb_link_speaker_non_vide / len(df_preprocessed)) * 100

print(f"Nombre de lignes avec link_speaker non vide : {nb_link_speaker_non_vide}")
print(f"Ratio par rapport à df_preprocessed : {ratio_link_speaker:.2f}%")

Nombre de lignes avec link_speaker non vide : 1505763
Ratio par rapport à df_preprocessed : 79.61%

In [36]:
df_preprocessed = df_preprocessed.copy()

df_preprocessed.loc[:, 'mp_id'] = (
    'PA' + df_preprocessed['link_speaker']
    .astype('string')
    .str.extract(r'/(\d+)\.asp(?:\?.*)?$', expand=False)
)

In [38]:
df_preprocessed[['link_speaker', 'mp_id']].head()
print(df_preprocessed.shape)
print(len(df_preprocessed))

(1891395, 15)
1891395

In [ ]:
df_preprocessed['link_speaker'].dropna().head(10).tolist()

['http://www.assemblee-nationale.fr/tribun/fiches_id/654.asp',
 'http://www.assemblee-nationale.fr/tribun/fiches_id/654.asp',
 'http://www.assemblee-nationale.fr/tribun/fiches_id/2424.asp',
 'http://www.assemblee-nationale.fr/tribun/fiches_id/654.asp',
 'http://www.assemblee-nationale.fr/tribun/fiches_id/2424.asp',
 'http://www.assemblee-nationale.fr/tribun/fiches_id/1991.asp',
 'http://www.assemblee-nationale.fr/tribun/fiches_id/2424.asp',
 'http://www.assemblee-nationale.fr/tribun/fiches_id/654.asp',
 'http://www.assemblee-nationale.fr/tribun/fiches_id/2424.asp',
 'http://www.assemblee-nationale.fr/tribun/fiches_id/654.asp']

In [41]:
print(df_preprocessed['mp_id'].notna().mean())

0.7960711538309025

In [42]:
df_preprocessed.loc[
    df_preprocessed['mp_id'].notna(),
    ['link_speaker', 'mp_id']
].head()

                                         link_speaker   mp_id
11  http://www.assemblee-nationale.fr/tribun/fiche...   PA654
18  http://www.assemblee-nationale.fr/tribun/fiche...   PA654
29  http://www.assemblee-nationale.fr/tribun/fiche...  PA2424
30  http://www.assemblee-nationale.fr/tribun/fiche...   PA654
31  http://www.assemblee-nationale.fr/tribun/fiche...  PA2424

In [43]:
df_preprocessed['mp_id'].notna().value_counts()

mp_id
True     1505685
False     385710
Name: count, dtype: int64

In [44]:
df_preprocessed.to_csv('../data/final/speech.csv')

In [45]:
# Lignes ayant un mp_id extrait depuis link_speaker
mask_mp_id_extrait = df_preprocessed['mp_id'].notna()

# Parmi ces lignes, vérifie si le mp_id existe dans politician
mask_bind_reussi = df_preprocessed.loc[mask_mp_id_extrait, 'mp_id'].isin(
    politician['mp_id'].dropna()
)

taux_bind = mask_bind_reussi.mean() * 100

print(f"Bind réussi parmi les mp_id extraits : {taux_bind:.3f} %")
print(f"Nombre de lignes testées : {mask_mp_id_extrait.sum():,}")
print(f"Nombre de lignes associées : {mask_bind_reussi.sum():,}")

Bind réussi parmi les mp_id extraits : 100.000 %
Nombre de lignes testées : 1,505,685
Nombre de lignes associées : 1,505,685